import "./globals.css";
import styles from "./styles.module.css";
import { Inter } from "next/font/google";
import Link from "next/link";
import Logout from "../components/logout";
import { Provider } from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <div className={styles.header}>
            <Link href="/">Learning Together</Link>
            <div className={styles.userIcon}></div>
            <div>
              <Link href="/register">新規登録</Link>
              <Link href="/login">ログイン</Link>
              <Logout />
            </div>
          </div>
          {children}
        </Provider>
      </body>
    </html>
  );
}
